### ISSUE TITLE
Is using at_exit to force cucumber to have failures lead to a non-zero exit code normal?

### ISSUE THREAD

**Issue by tansaku** [cucumber/cucumber-ruby#1004]
## Summary

Recently we've been confused on our OS project LocalSupport, because individual cucumber scenario failures were not causing the travis CI build to fail - causing us to miss errors and merge things in when they weren't yet ready.

The travis support folks identified that our task ```rake test_with_coveralls``` was not giving a non-zero exit code, which is what Travis takes to be an indication of build failure:

https://github.com/travis-ci/travis-ci/issues/5945

our rake task runs our specs, cukes and then pushed coverage to coveralls:

```rb
task :test_with_coveralls => [:spec, :cucumber, 'coveralls:push']
```

## Expected Behavior

I've been reading various discussions about cucumber exit codes:

* https://github.com/cucumber/cucumber-ruby/issues/635
* http://stackoverflow.com/questions/8559694/cucumber-background-fails-still-exits-with-code-0
* https://groups.google.com/forum/#!topic/cukes/w86pPYPtc5k

and I'm not sure that I follow all the arguments, but in the past it certainly seemed that our CI (in this case travis) would reliably fail the build when cukes (or specs) failed.  Maybe this is a Travis issue, but anyway, I would expect a failing cuke to lead to a non-zero exit code.

## Current Behavior

Currently (checking with `echo $?`) it seems like cucumber (in our project https://github.com/AgileVentures/LocalSupport) always generates a zero exit code when we run in batch

## Possible Solution

In order to fix this and ensure that the travis CI build fails, (partly inspired by http://collectiveidea.com/blog/archives/2015/01/27/cucumber-exiting-with-0-on-failure/) we added the following to our cucumber env.rb:

```rb
After do |s| 
  Cucumber.wants_to_quit = true if s.failed?
end

at_exit do
  exit 1 if Cucumber.wants_to_quit
end
```

this seems to give us the expected behaviour of a non-zero exit code whenever an individual cuke fails

## Steps to Reproduce (for bugs)

Not sure that this is a bug per se.  There are a lot of moving parts, and I'm not clear that I'm seeing the whole picture.  You can see an example of a build that was green here:

https://travis-ci.org/AgileVentures/LocalSupport/builds/145792711

That still contained a failing cuke scenario.

Basic steps to reproduce though are to run cucumber scenarios in batch and check the exit code with `echo $?`

## Context & Motivation

The main motivation for me here is that I think we really need our CI to fail when any specs or cukes fail. My sincere apologies if this is actually nothing to do with Cucumber.  I thought I had the above fix (with at_exit) as a solution, but now our jasmine:ci is failing on Travis and I can't work out why, or even if that is related (I posted a separate ticket to Travis about that).  My main question here is whether our approach using `at_exit` is sensible? dangerous? a hack?

It would be great to know what the cucumber teams' latest thinking is about when it is appropriate to terminate a batch test run with a non-zero exit status. 

## Your Environment

* Version used: Cucumber 2.4 (I just upgraded us to this to see if that would help)
* Operating System and version: Locally I'm using OSX 10.11.5 - and I think Travis CI is Ubuntu 12.0.4 full details here: https://docs.travis-ci.com/user/ci-environment/
* Link to your project: https://github.com/AgileVentures/LocalSupport

Many thanks in advance, and sincere apologies if this is the wrong place to ask the above questions.

**Comment by tansaku** [comment]
follow up - I also notice that in another project that I get the expected exit codes:

```
→ echo $?
0
[tansaku@Samuels-MacBook-Pro:~/Documents/GitHub/AgileVentures/projectscope_mvp (2_acceptance_test_for_viewing_project_metrics)]$ 
→ bec
Using the default profile...
.......................F

(::) failed steps (::)

expected to find text "aasdasdadasdadasdad" in "Project List Project Name CodeClimate Metric Github Metric LocalSupport 3.20 code climate code climate 3.2 3.2 0.63 WebsiteOne 3.50 code climate code climate 3.5 3.5 0.28 New Project" (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/web_steps.rb:108:in `/^(?:|I )should see "([^"]*)"$/'
features/view_metrics.feature:40:in `And I should see "aasdasdadasdadasdad"'

Failing Scenarios:
cucumber features/view_metrics.feature:33 # Scenario: update metrics for projects

3 scenarios (1 failed, 2 passed)
24 steps (1 failed, 23 passed)
0m5.115s
[tansaku@Samuels-MacBook-Pro:~/Documents/GitHub/AgileVentures/projectscope_mvp (2_acceptance_test_for_viewing_project_metrics)]$ 
→ echo $?
1
```

which makes me think that maybe there is something subtle messed up in our env.rb in LocalSupport: 

https://github.com/AgileVentures/LocalSupport/blob/004000f3709db70a7160ad172661f4bfd3f72d19/features/support/env.rb

**Comment by tansaku** [comment]
while checking LocalSupport we get a different behaviour:

```
[tansaku@Samuels-MacBook-Pro:~/Documents/GitHub/AgileVentures/LocalSupport (119350175_ensure_cuke_failure_leads_to_correct_exit_code)]$ 
→ bec
[Coveralls] Using SimpleCov's 'rails' settings.
/Users/tansaku/Documents/GitHub/AgileVentures/LocalSupport/features/step_definitions/navigation_steps.rb:35: warning: key "contributors" is duplicated and overwritten on line 43
Using the default profile...
...........................................................................................................................................................................................................................................................................................................................................................................................................................I, [2016-08-10T18:24:37.785585 #25278]  INFO -- : Start emails import
I, [2016-08-10T18:24:37.922723 #25278]  INFO -- : Emails import finished
.................................................................................[DEPRECATION] Capybara::Webkit::Driver#browser is deprecated.
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

282 scenarios (282 passed)
2259 steps (2259 passed)
1m27.090s
[tansaku@Samuels-MacBook-Pro:~/Documents/GitHub/AgileVentures/LocalSupport (119350175_ensure_cuke_failure_leads_to_correct_exit_code)]$ 
→ echo $?
0
[tansaku@Samuels-MacBook-Pro:~/Documents/GitHub/AgileVentures/LocalSupport (119350175_ensure_cuke_failure_leads_to_correct_exit_code)]$ 
→ bec
[Coveralls] Using SimpleCov's 'rails' settings.
/Users/tansaku/Documents/GitHub/AgileVentures/LocalSupport/features/step_definitions/navigation_steps.rb:35: warning: key "contributors" is duplicated and overwritten on line 43
Using the default profile...
...........................................................................................................................................................................................................................................................................................................................................................................................................................I, [2016-08-10T18:27:43.732001 #25320]  INFO -- : Start emails import
I, [2016-08-10T18:27:43.857343 #25320]  INFO -- : Emails import finished
.........................................................F........................[DEPRECATION] Capybara::Webkit::Driver#browser is deprecated.
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

(::) failed steps (::)

expected to find text "asdasdqedwqsadqawdqwased13qwas" in "Search for local voluntary and community organisations Home Organisations Admin Invite Users to become admin of Organisations Registered Users Invited Users Deleted Users Pending Proposed Edits Pending Proposed Organisations superadmin@myorg.com Log out × Mail template has been updated Invite Users Select All The Following email will be sent when a user is invited: Test message Accept invitation Nothing Edit template Name Email Harrow Community Network provided by Voluntary Action Harrow Co-operative&nbsp Powered by | New Organisation |" (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/basic_steps.rb:338:in `/^I should( not)? see "([^"]*)"$/'
features/admin/organisation_reports/edit_email_templates.feature:25:in `And I should see "asdasdqedwqsadqawdqwased13qwas"'

Failing Scenarios:
cucumber features/admin/organisation_reports/edit_email_templates.feature:19 # Scenario: Super Admin can edit email template of invitation instructions

282 scenarios (1 failed, 281 passed)
2260 steps (1 failed, 2259 passed)
1m27.604s
[tansaku@Samuels-MacBook-Pro:~/Documents/GitHub/AgileVentures/LocalSupport (119350175_ensure_cuke_failure_leads_to_correct_exit_code)]$ 
→ echo $?
0
```

**Comment by tansaku** [comment]
I just did a git bisect hunt through our LocalSupport project and it seems that this always zero exit first started happening when we upgraded to ruby 2.3.0:

https://github.com/AgileVentures/LocalSupport/commit/fc23f81db35f5948a7c680e0c4bd85b90f687f93

**Comment by tansaku** [comment]
and upgrading to ruby 2.3.1 appears to fix the issue without need for any changes to the env.rb file ...

**Comment by mattwynne** [comment]
Thanks for keeping us informed and closing the issue @tansaku. I'm glad you figured it out!
