### ISSUE TITLE
Error viewing Cucumber-JVM .json reports when using Scenario Outline

### ISSUE THREAD

**Issue by maddyjakk** [cucumber/cucumber-ruby#1065]
Hi,

I use Cucumber+Ruby framework to execute tests and generate .html and .json reports. I'm using Jenkins Cucumber-JVM plugin to view the results/graphs generated out of the cucumber.json report. 

For features with Scenario Outlines, I get the following error. Is there a way to work around the issue? (I can email the .json file if needed)
java.lang.NullPointerException
	at net.masterthought.cucumber.json.Element.calculateStatus(Element.java:146)
	at net.masterthought.cucumber.json.Element.setMetaData(Element.java:128)
	at net.masterthought.cucumber.json.Feature.setMetaData(Feature.java:151)
	at net.masterthought.cucumber.ReportParser.setMetadata(ReportParser.java:91)
	at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:61)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:56)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:125)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:70)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

Trying to generate report from following files. Make sure they are valid cucumber report files:
           /var/lib/jenkins/jobs/regression/builds/131/cucumber20161221-154148.json

The broken .json reports cause Jenkins builds to break even though all the tests are successful and don't offer a way to view the results in the event .html results are unavailable to be mailed out via Jenkins Server.

Environment:
* Version used: Ruby 2.3.0, cucumber: 2.0.0
* Operating System and version: RHEL7

Appreciate any support!

**Comment by vveliev** [comment]
I don't think you are posted in correct project....
[https://github.com/jenkinsci/cucumber-reports-plugin](url)

**Comment by maddyjakk** [comment]
Thanks, I've added an issue in the correct project.
 https://github.com/jenkinsci/cucumber-reports-plugin/issues/107

**Comment by brasmusson** [comment]
@maddyjakk Note, that in Cucumber v2.0.0 the `--expand` options is still needed to produce json files suitable for the Jenkins Cucumber-JVM plugin - when using Scenario Outlines. When using the Json Formatter it would be better to at least use cucumber v2.0.1, where the Json Formatter is re-written against the new formatter-API (#851) - so the `--expand` options is no longer needed, or even better to use Cucumber v2.3.3, where also the fixes for the Json Formatter of #948 and #949 are included, see [History.md](https://github.com/cucumber/cucumber-ruby/blob/master/History.md).

**Comment by maddyjakk** [comment]
@brasmusson - Perfect, that worked! Thank you. I've used the --expand option for now as I'm using v2.0.0 and I see the cucumber reports generated without any exceptions.
