### ISSUE TITLE
v3.0.0.pre.1: stepdefs formatter crashes with undefined method step_definition for nil:NilClass

### ISSUE THREAD

**Issue by roschaefer** [cucumber/cucumber-ruby#1120]
Following @brasmusson suggestions in #953:

```sh
$ cucumber --version
3.0.0.pre.1

```

```sh
$ cucumber -f stepdefs --dry-run

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------undefined method `step_definition' for nil:NilClass
Did you get the ID of the event wrong? Try one of these:
test_case_starting
test_step_starting
test_step_finished
test_case_finished
step_definition_registered
step_match
test_run_finished (NoMethodError)
/home/robert/.gem/ruby/2.4.0/gems/cucumber-3.0.0.pre.1/lib/cucumber/formatter/usage.rb:41:in `on_test_step_finished'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/event_bus.rb:32:in `block in broadcast'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/event_bus.rb:32:in `each'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/event_bus.rb:32:in `broadcast'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/event_bus.rb:37:in `method_missing'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/runner.rb:28:in `test_step'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/step.rb:17:in `describe_to'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/case.rb:27:in `block (3 levels) in describe_to'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/case.rb:26:in `each'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/case.rb:26:in `block (2 levels) in describe_to'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/case.rb:120:in `compose_around_hooks'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/case.rb:25:in `block in describe_to'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/runner.rb:19:in `test_case'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/case.rb:24:in `describe_to'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-3.0.0.pre.1/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/case.rb:24:in `describe_to'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/filter.rb:57:in `test_case'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-3.0.0.pre.1/lib/cucumber/filters/retry.rb:18:in `test_case'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/case.rb:24:in `describe_to'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-3.0.0.pre.1/lib/cucumber/filters/quit.rb:12:in `test_case'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/case.rb:24:in `describe_to'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/filters/locations_filter.rb:18:in `block in done'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `each'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `done'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/filter.rb:62:in `done'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/test/filters/tag_filter.rb:19:in `done'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/compiler.rb:24:in `done'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core/gherkin/parser.rb:37:in `done'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core.rb:32:in `parse'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-core-2.0.0/lib/cucumber/core.rb:21:in `compile'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-3.0.0.pre.1/lib/cucumber/runtime.rb:69:in `run!'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-3.0.0.pre.1/lib/cucumber/cli/main.rb:33:in `execute!'
/home/robert/.gem/ruby/2.4.0/gems/cucumber-3.0.0.pre.1/bin/cucumber:8:in `<top (required)>'
/home/robert/.gem/ruby/2.4.0/bin/cucumber:22:in `load'
/home/robert/.gem/ruby/2.4.0/bin/cucumber:22:in `<main>'
```

**Comment by brasmusson** [comment]
The likely cause of this is #1041, do when it is fixed this will be fixed.

**Comment by brasmusson** [comment]
#1041 is fixed so this should work v3.0.0

**Comment by lastobelus** [comment]
Yesterday's release is still exhibiting this problem:

```
cucumber features/navigation/main-menu.feature --format usage
```

```
undefined method `step_definition' for nil:NilClass (NoMethodError)
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/formatter/usage.rb:41:in `on_test_step_finished'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:34:in `block in broadcast'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:34:in `each'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:34:in `broadcast'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:40:in `method_missing'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:35:in `around_hook'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/around_hook.rb:12:in `describe_to'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:120:in `block (2 levels) in compose_around_hooks'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:121:in `compose_around_hooks'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:26:in `block in describe_to'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:19:in `test_case'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/prepare_world.rb:12:in `test_case'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:57:in `test_case'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/retry.rb:18:in `test_case'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/quit.rb:12:in `test_case'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `block in done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:19:in `map'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:19:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/locations_filter.rb:20:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/compiler.rb:24:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/gherkin/parser.rb:37:in `done'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core.rb:32:in `parse'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core.rb:21:in `compile'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:74:in `run!'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:33:in `execute!'
/Users/lasto/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/bin/cucumber:9:in `<top (required)>'
/Users/lasto/.rvm/gems/ruby-2.4.2/bin/cucumber:23:in `load'
/Users/lasto/.rvm/gems/ruby-2.4.2/bin/cucumber:23:in `<main>'
/Users/lasto/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/lasto/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rlgomes** [comment]
FYI to those hitting this I've run into the issue and finally identified that its because you have undefined steps... ie you if you run `cucumber --dry-run your_feature_directory` you'll see the indication of which steps are missing that lead to the `cucumber --format stepdefs` blowing up. That said stepdefs could handle this more gracefully but that was the issue I was running into and once I fixed the typos in my feature files (because I wasn't missing any step) the `stepdefs` just worked.
