### ISSUE TITLE
Too many open files - getcwd (Errno::EMFILE)

### ISSUE THREAD

**Issue by suryasri13** [cucumber/cucumber-ruby#1122]
I'm trying to post something to the api and verifying if the values are posted correctly in the DB.

In this process, when I'm trying to verify values in the db I get "Too many open files - getcwd (Errno::EMFILE)" error.

I use faraday gem to post a request and mysql2 gem to check the db values.

The complete  backtrace of the error is as below

Too many open files - getcwd (Errno::EMFILE)
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/backtrace_filter.rb:21:in `pwd'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/backtrace_filter.rb:21:in `exception'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:1003:in `filtered_exception'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:1007:in `filtered_step_exception'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:995:in `step_exception'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:977:in `step_invocation'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:191:in `build_step_invocation'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:373:in `print_step'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:239:in `after_test_step'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:95:in `after_test_step'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:37:in `after_test_step'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:34:in `around_hook'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/filters/quit.rb:11:in `test_case'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/myname/.rvm/gems/ruby-2.3.3/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/myname/.rvm/gems/ruby-2.3.3/bin/cucumber:22:in `load'
/Users/myname/.rvm/gems/ruby-2.3.3/bin/cucumber:22:in `<main>'
/Users/myname/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/myname/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by suryasri13** [comment]
ulimit -n 1024 has resolved the issue.
