### ISSUE TITLE
Error in executing the cucumber instruction on the command line

### ISSUE THREAD

**Issue by jniosdeveloper** [cucumber/cucumber-ruby#1375]
Hello, when my project is finally executed by cucumber, an error is reported. The error is:

```
cannot load such file -- cucumber/ast (LoadError)
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
/Users/jackie-pc/Desktop/AutoTestDemo-master/features/support/env.rb:9:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cucumber-4.0.0.rc.3/lib/cucumber/glue/registry_and_more.rb:111:in `load_code_file'
/Library/Ruby/Gems/2.6.0/gems/cucumber-4.0.0.rc.3/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/Library/Ruby/Gems/2.6.0/gems/cucumber-4.0.0.rc.3/lib/cucumber/runtime/support_code.rb:81:in `block in load_files!'
/Library/Ruby/Gems/2.6.0/gems/cucumber-4.0.0.rc.3/lib/cucumber/runtime/support_code.rb:80:in `each'
/Library/Ruby/Gems/2.6.0/gems/cucumber-4.0.0.rc.3/lib/cucumber/runtime/support_code.rb:80:in `load_files!'
/Library/Ruby/Gems/2.6.0/gems/cucumber-4.0.0.rc.3/lib/cucumber/runtime.rb:242:in `load_step_definitions'
/Library/Ruby/Gems/2.6.0/gems/cucumber-4.0.0.rc.3/lib/cucumber/runtime.rb:66:in `run!'
/Library/Ruby/Gems/2.6.0/gems/cucumber-4.0.0.rc.3/lib/cucumber/cli/main.rb:29:in `execute!'
/Library/Ruby/Gems/2.6.0/gems/cucumber-4.0.0.rc.3/bin/cucumber:9:in `<top (required)>'
/usr/local/bin/cucumber:23:in `load'
/usr/local/bin/cucumber:23:in `<main>'
```

I want to know why? How can I solve it

**Comment by luke-hill** [comment]
can you create an MVCE. Ideally this would be in the form of a small git repo we could pull down and run by doing `bundle exec cucumber`

**Comment by aslakhellesoy** [comment]
Judging from your backtrace I can see that `/Users/jackie-pc/Desktop/AutoTestDemo-master/features/support/env.rb` file does `require 'cucumber/ast'`. This is an internal class that you shouldn't be referencing, and it's been removed in version 4.0.0.rc.3.
