### ISSUE TITLE
using --dry-run option with --format message --out="http://<url>/" is throwing undefined method `id' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ericlin0122** [cucumber/cucumber-ruby#1488]
**Describe the bug**
using `--dry-run` option and set --format message output to HTTPIO is throwing:
```
undefined method `id' for nil:NilClass (NoMethodError)
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-5.2.0/lib/cucumber/formatter/query/test_case_started_by_test_case.rb:22:in `test_case_started_id_by_test_case'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-5.2.0/lib/cucumber/formatter/message_builder.rb:251:in `test_case_started_id'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-5.2.0/lib/cucumber/formatter/message_builder.rb:177:in `on_test_step_started'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/event_bus.rb:34:in `block in broadcast'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/event_bus.rb:34:in `each'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/event_bus.rb:34:in `broadcast'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/event_bus.rb:40:in `method_missing'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/runner.rb:28:in `test_step'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/step.rb:23:in `describe_to'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/case.rb:31:in `block (3 levels) in describe_to'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/case.rb:30:in `each'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/case.rb:30:in `block (2 levels) in describe_to'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/case.rb:81:in `compose_around_hooks'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/case.rb:29:in `block in describe_to'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/runner.rb:19:in `test_case'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-5.2.0/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/filters/locations_filter.rb:18:in `block in done'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/filters/locations_filter.rb:17:in `each'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/filters/locations_filter.rb:17:in `done'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/filter.rb:62:in `done'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/compiler.rb:31:in `done'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core/gherkin/parser.rb:46:in `done'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core.rb:35:in `parse'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-core-8.0.1/lib/cucumber/core.rb:24:in `compile'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-5.2.0/lib/cucumber/runtime.rb:79:in `run!'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-5.2.0/lib/cucumber/cli/main.rb:29:in `execute!'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/gems/cucumber-5.2.0/bin/cucumber:9:in `<top (required)>'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/bin/cucumber:23:in `load'
/Users/yuchihli/.rvm/gems/ruby-2.6.3/bin/cucumber:23:in `<top (required)>'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/bin/bundle:23:in `load'
/Users/yuchihli/.rvm/rubies/ruby-2.6.3/bin/bundle:23:in `<main>'

```

**To Reproduce**
1. run any cucumber test with the following option:
`cucumber features/tests/test.feature --dry-run --format message --out="http://<url> -X POST -H Content-Type:text/ndjson"`

**Expected behavior**
a request should be send to the server after dry run completes, but it's not. 

the soon deprecated json formatter HTTPIO is working properly with `--dry-run`, i would expect message formatter should be working as well. 
i.e. this is working:
```
cucumber features/tests/backup_restore/latest/backup_restore_custom_download.feature --dry-run --format json --out="http://192.168.99.102:30081/api/v1/regression/report/123 -X POST -H Content-Type:text/json"
```

**Context & Motivation**

How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.

we are building a custom test runner to work with k8s. our goal is to fetch a list of features under predefined rake tests using dry-run option so that we know what we are dealing with and having flexible option for users to select what they want to run/re-run.

**Screenshots**

**Your Environment**
 - Versions used [e.g 5.0.0]
5.2.0
 - Operating System and version [e.g. * Operating System and version:]
macOS 10.13.6
 - Build tool (if applicable)
cmd
**Additional context**
Add any other context about the problem here

**Comment by meliesan** [comment]
I have the same issue.
Simply running:
`cucumber --dry-run --tags @mytag` in console, I get same error
