### ISSUE TITLE
Upgrade to 4.1.0 breaks javascript version of a feature test

### ISSUE THREAD

**Issue by bunnymatic** [cucumber/cucumber-ruby#1495]
Upgrading to 4.1.0 from 3.1.2 breaks test that were previously running fine around a simple login feature.

I'm on Rails 6.1, capybara 3.33.0, cucumber 4.1.0 (previously 3.1.2) and as of this upgrade, the tests that execute a simple login (visit the login page, fill in username and password) started to fail but only when `@javascript` is turned on.  The server reports "invalid password".  

**Reproducing**
I don't have a simple repo to share to easily reproduce this but I wonder if you might know what behavior might have changed that would lead to this.  I'll include some code snippets here and try to build a dummy app where I can better show the problem.  

The basic feature looks like this:

```
Feature: As a user I can login

Background:
  Given an account has been created
  Given I visit the login page

Scenario: login with good info
  When I fill in valid credentials
  And I click "Sign In"
  Then I see that I'm logged in
  And I click on the first "sign out" link
  Then I see that I'm logged out

@javascript
Scenario: login with good info
  When I fill in valid credentials
  And I click "Sign In"
  Then I see that I'm logged in
  And I click on the first "sign out" link
  Then I see that I'm logged out
```

The `fill in valid credentials` through a few steps boils down to
```
  fill_in('Username/Email', with: login)
  fill_in('Password', with: pass)
```

The first feature, with javascript turned off, works just fine.  The second does not.  The server which is validating the login reports `invalid user/pass combo`.  I've verified that the parameters sent down to the `UserSession` model are the same in both cases.  I'm using `authlogic` under the hood but that gem has *not* been upgraded.

The failure is that "Then I see that I'm logged in" fails because the user is not successfully logged in but only in the version with `@javascript` turned on.

Could this be something about authorization headers or something?

I'll let you know if I can get this together in a smaller shareable repo scenario.  But if you have any insights on where the problem might be, I'm happy to do some more digging.

**Expected behavior**
I expect the tests to pass as they do with the previous version (3.1.2)

**Your Environment**
 - cucumber 4.1.0 - note versions 3.1.2 and 3.2.0 both work just fine
 - Gemfile diff - i tried to upgrade stepwise until i saw the issue - but that was basically 3.1.2 => 3.2.0 => 4.1.0
 - Operating System and version: Mac Mojave 10.14.6
 - brew/ruby/bundler

**Motivation**

I'm trying to get this project up to the latest (v5.x) and this is not allowing that to happen.

**Additional context**
This is the Gemfile.lock diff between the success and failure.  You will notice I pinned capybara to make sure that upgrade did not affect things as well as pinning `cucumber`.

```
diff --git a/Gemfile.lock b/Gemfile.lock
index eed8fbc3..5fc9b962 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -91,7 +91,6 @@ GEM
       aws-sigv4 (~> 1.1)
     aws-sigv4 (1.1.3)
       aws-eventstream (~> 1.0, >= 1.0.2)
-    backports (3.17.2)
     better_errors (2.7.1)
       coderay (>= 1.0.0)
       erubi (>= 1.0.0)
@@ -152,32 +151,47 @@ GEM
     crack (0.4.3)
       safe_yaml (~> 1.0.0)
     crass (1.0.6)
-    cucumber (3.1.2)
-      builder (>= 2.1.2)
-      cucumber-core (~> 3.2.0)
-      cucumber-expressions (~> 6.0.1)
-      cucumber-wire (~> 0.0.1)
-      diff-lcs (~> 1.3)
-      gherkin (~> 5.1.0)
-      multi_json (>= 1.7.5, < 2.0)
-      multi_test (>= 0.1.2)
-    cucumber-core (3.2.1)
-      backports (>= 3.8.0)
-      cucumber-tag_expressions (~> 1.1.0)
-      gherkin (~> 5.0)
-    cucumber-expressions (6.0.1)
-    cucumber-rails (2.0.0)
-      capybara (>= 2.12, < 4)
-      cucumber (>= 3.0.2, < 4)
-      mime-types (>= 2.0, < 4)
+    cucumber (4.1.0)
+      builder (~> 3.2, >= 3.2.3)
+      cucumber-core (~> 7.1, >= 7.1.0)
+      cucumber-create-meta (~> 1.0.0, >= 1.0.0)
+      cucumber-cucumber-expressions (~> 10.1, >= 10.1.0)
+      cucumber-gherkin (~> 14.0, >= 14.0.1)
+      cucumber-html-formatter (~> 7.0, >= 7.0.0)
+      cucumber-messages (~> 12.2, >= 12.2.0)
+      cucumber-wire (~> 3.1, >= 3.1.0)
+      diff-lcs (~> 1.3, >= 1.3, < 1.4)
+      multi_test (~> 0.1, >= 0.1.2)
+      sys-uname (~> 1.0, >= 1.0.2)
+    cucumber-core (7.1.0)
+      cucumber-gherkin (~> 14.0, >= 14.0.1)
+      cucumber-messages (~> 12.2, >= 12.2.0)
+      cucumber-tag-expressions (~> 2.0, >= 2.0.4)
+    cucumber-create-meta (1.0.0)
+      cucumber-messages (~> 12.2, >= 12.2.0)
+      sys-uname (~> 1.2, >= 1.2.1)
+    cucumber-cucumber-expressions (10.3.0)
+    cucumber-gherkin (14.2.0)
+      cucumber-messages (~> 12.4, >= 12.4.0)
+    cucumber-html-formatter (7.2.0)
+      cucumber-messages (~> 12.4, >= 12.4.0)
+    cucumber-messages (12.4.0)
+      protobuf-cucumber (~> 3.10, >= 3.10.8)
+    cucumber-rails (2.2.0)
+      capybara (>= 2.18, < 4)
+      cucumber (>= 3.0.2, < 6)
+      mime-types (~> 3.2)
       nokogiri (~> 1.8)
-      railties (>= 4.2, < 7)
-    cucumber-tag_expressions (1.1.1)
-    cucumber-wire (0.0.1)
+      rails (>= 5.0, < 7)
+    cucumber-tag-expressions (2.0.4)
+    cucumber-wire (3.1.0)
+      cucumber-core (~> 7.1, >= 7.1.0)
+      cucumber-cucumber-expressions (~> 10.1, >= 10.1.0)
+      cucumber-messages (~> 12.2, >= 12.2.0)
     dalli (2.7.10)
     database_cleaner (1.8.5)
     debug_inspector (0.0.3)
-    diff-lcs (1.4.4)
+    diff-lcs (1.3)
     docile (1.3.2)
     dotenv (2.7.6)
     dotenv-rails (2.7.6)
@@ -224,7 +238,6 @@ GEM
     geokit-rails (2.3.1)
       geokit (~> 1.5)
       rails (>= 3.0)
-    gherkin (5.1.0)
     gibbon (3.3.4)
       faraday (>= 0.16.0)
       multi_json (>= 1.11.0)
@@ -270,9 +283,10 @@ GEM
     marcel (0.3.3)
       mimemagic (~> 0.3.2)
     method_source (1.0.0)
+    middleware (0.1.0)
     mime-types (3.3.1)
       mime-types-data (~> 3.2015)
-    mime-types-data (3.2020.0512)
+    mime-types-data (3.2020.1104)
     mimemagic (0.3.5)
     mini_mime (1.0.2)
     mini_portile2 (2.5.0)
@@ -304,7 +318,12 @@ GEM
     postmark-rails (0.20.0)
       actionmailer (>= 3.0.0)
       postmark (~> 1.15)
-    public_suffix (4.0.5)
+    protobuf-cucumber (3.10.8)
+      activesupport (>= 3.2)
+      middleware
+      thor
+      thread_safe
+    public_suffix (4.0.6)
     puma (4.3.5)
       nio4r (~> 2.0)
     qr4r (0.6.0)
@@ -366,7 +385,7 @@ GEM
     rdiscount (2.2.0.1)
     recaptcha (5.5.0)
       json
-    regexp_parser (1.7.1)
+    regexp_parser (1.8.2)
     request_store (1.5.0)
       rack (>= 1.4)
     require_all (3.0.0)
@@ -455,11 +474,14 @@ GEM
     sshkit (1.21.0)
       net-scp (>= 1.1.2)
       net-ssh (>= 2.8.0)
+    sys-uname (1.2.2)
+      ffi (~> 1.1)
     temple (0.8.2)
     terrapin (0.6.0)
       climate_control (>= 0.0.3, < 1.0)
     test-prof (0.11.3)
     thor (1.0.1)
+    thread_safe (0.3.6)
     tilt (2.0.10)
     tzinfo (2.0.4)
       concurrent-ruby (~> 1.0)
@@ -506,11 +528,11 @@ DEPENDENCIES
   capistrano-rails
   capistrano-rbenv
   capistrano3-puma
-  capybara
+  capybara (= 3.33.0)
   capybara-email
   capybara-screenshot
   capybara-select-2
-  cucumber
+  cucumber (= 4.1.0)
   cucumber-rails
   dalli
   database_cleaner
```

Not sure if this would also be helpful (probably not) but this is the test output
```
be cucumber features/users/logintrim.feature
Elasticsearch url: http://localhost:9250
Using the default profile...
Feature: As a user I can login

  Background:                         # features/users/logintrim.feature:3
Capybara starting Puma...
* Version 4.3.5 , codename: Mysterious Traveller
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:65316
    Given an account has been created # features/step_definitions/factory_steps.rb:3
    Given I visit the login page      # features/step_definitions/shared_steps.rb:73

  @javascript
  Scenario: login with good info             # features/users/logintrim.feature:15
    When I fill in valid credentials         # features/step_definitions/user_steps.rb:44
    And I click "Sign In"                    # features/step_definitions/shared_steps.rb:186
    Then I see that I'm logged in            # features/step_definitions/user_steps.rb:48
      execution expired (Timeout::Error)
      ./features/support/flash_message_matchers.rb:10:in `block (3 levels) in <top (required)>'
      ./features/support/capybara_helpers.rb:22:in `block (2 levels) in wait_until'
      ./features/support/capybara_helpers.rb:21:in `loop'
      ./features/support/capybara_helpers.rb:21:in `block in wait_until'
      ./features/support/capybara_helpers.rb:20:in `wait_until'
      ./features/support/flash_message_matchers.rb:9:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/user_steps.rb:49:in `/^I see that I'm logged in$/'
      ./features/support/capybara.rb:48:in `block in <top (required)>'
      features/users/logintrim.feature:18:in `I see that I'm logged in'
    And I click on the first "sign out" link # features/step_definitions/shared_steps.rb:218
    Then I see that I'm logged out           # features/step_definitions/user_steps.rb:61
    HTML screenshot: /Users/jon/projects/mau/tmp/capybara/screenshot_2021-01-09-14-07-40.520.html
    Image screenshot: /Users/jon/projects/mau/tmp/capybara/screenshot_2021-01-09-14-07-40.520.png

WARNING: #embed(file, mime_type, label) is deprecated and will be removed after version 5.0.0. Please use attach(file, media_type) instead.
(Called from /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-screenshot-1.0.24/lib/capybara-screenshot/cucumber.rb:24:in `block (2 levels) in <top (required)>')

  Scenario: login with good info             # features/users/logintrim.feature:7
    When I fill in valid credentials         # features/step_definitions/user_steps.rb:44
    And I click "Sign In"                    # features/step_definitions/shared_steps.rb:186
    Then I see that I'm logged in            # features/step_definitions/user_steps.rb:48
    And I click on the first "sign out" link # features/step_definitions/shared_steps.rb:218
    Then I see that I'm logged out           # features/step_definitions/user_steps.rb:61

Failing Scenarios:
cucumber features/users/logintrim.feature:15 # Scenario: login with good info

2 scenarios (1 failed, 1 passed)
14 steps (1 failed, 2 skipped, 11 passed)
0m10.547s
```

**Comment by bunnymatic** [comment]
Sadly I spent some time trying to reproduce in a clean repo that i can share (using what I think should be a similar setup) and can't seem to reproduce it.  So... if you have any clues on why having the `@javascript` turned on could change anything, I'd love to hear it.  Related to that, I found it behaves the same with firefox and chrome drivers - breaks the same way in both.  

I'll continue to try to reproduce in a repository I can share.
