### ISSUE TITLE
undefined method `new' for BigDecimal:Class (NoMethodError)

### ISSUE THREAD

**Issue by markblasdls** [cucumber/cucumber-ruby#1511]
**Describe the bug**
- Upgrading big decimal from 1.3.5 to 3.0.0 or 2.0.x shows error undefined method `new' for BigDecimal:Class (NoMethodError) when running cucumber

**To Reproduce**
1. Install cucumber
2. Add bigdecimal 3.0.0 or 2.0.x
3. run cucumber

**Expected behavior**
Should run Cucumber

**Context & Motivation**
This issue will be affecting our future rails and other gem upgrades. Our app is from rails 5 and currently in rails 6.0.3.5. In order for us to move to rails 6.1 and ruby 3. We have to make sure our test cases(cucumber) work fine.

**Your Environment**
 rails version 6.0.3.5
 ruby 2.7.2
 cucumber 5.3.0
 bigdecimal 3.0.0

**Additional context**
undefined method `new' for BigDecimal:Class (NoMethodError)
/Users/blas/.rvm/gems/ruby-2.7.2/bundler/gems/shoulda-matchers-4b160bd19ecc/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:273:in `<class:ValidateInclusionOfMatcher>'
/Users/blas/.rvm/gems/ruby-2.7.2/bundler/gems/shoulda-matchers-4b160bd19ecc/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:270:in `<module:ActiveModel>'
/Users/blas/.rvm/gems/ruby-2.7.2/bundler/gems/shoulda-matchers-4b160bd19ecc/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:6:in `<module:Matchers>'
/Users/blas/.rvm/gems/ruby-2.7.2/bundler/gems/shoulda-matchers-4b160bd19ecc/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:5:in `<module:Shoulda>'
/Users/blas/.rvm/gems/ruby-2.7.2/bundler/gems/shoulda-matchers-4b160bd19ecc/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:4:in `<top (required)>'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/bundler/gems/shoulda-matchers-4b160bd19ecc/lib/shoulda/matchers/active_model.rb:17:in `<top (required)>'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/bundler/gems/shoulda-matchers-4b160bd19ecc/lib/shoulda/matchers.rb:13:in `<top (required)>'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/bundler/gems/shoulda-matchers-4b160bd19ecc/lib/shoulda-matchers.rb:1:in `<top (required)>'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.3/lib/bundler/runtime.rb:66:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.3/lib/bundler/runtime.rb:66:in `block (2 levels) in require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.3/lib/bundler/runtime.rb:61:in `each'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.3/lib/bundler/runtime.rb:61:in `block in require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.3/lib/bundler/runtime.rb:50:in `each'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.3/lib/bundler/runtime.rb:50:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/bundler-2.2.3/lib/bundler.rb:174:in `require'
/Users/blas/Documents/projects/project-name/config/application.rb:7:in `<top (required)>'
/Users/blas/Documents/projects/project-name//config/environment.rb:2:in `require_relative'
/Users/blas/Documents/projects/project-name//config/environment.rb:2:in `<top (required)>'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-rails-2.2.0/lib/cucumber/rails.rb:12:in `<top (required)>'
/Users/blas/Documents/projects/project-name//features/support/env.rb:7:in `require'
/Users/blas/Documents/projects/project-name//features/support/env.rb:7:in `<top (required)>'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-5.3.0/lib/cucumber/glue/registry_and_more.rb:121:in `require'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-5.3.0/lib/cucumber/glue/registry_and_more.rb:121:in `load_code_file'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-5.3.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-5.3.0/lib/cucumber/runtime/support_code.rb:81:in `block in load_files!'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-5.3.0/lib/cucumber/runtime/support_code.rb:80:in `each'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-5.3.0/lib/cucumber/runtime/support_code.rb:80:in `load_files!'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-5.3.0/lib/cucumber/runtime.rb:255:in `load_step_definitions'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-5.3.0/lib/cucumber/runtime.rb:72:in `run!'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-5.3.0/lib/cucumber/cli/main.rb:29:in `execute!'
/Users/blas/.rvm/gems/ruby-2.7.2/gems/cucumber-5.3.0/bin/cucumber:9:in `<top (required)>'
/Users/blas/.rvm/gems/ruby-2.7.2/bin/cucumber:23:in `load'
/Users/blas/.rvm/gems/ruby-2.7.2/bin/cucumber:23:in `<main>'
/Users/blas/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `eval'
/Users/blas/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `<main>'

**Comment by luke-hill** [comment]
do you have an MVCE (Ideally in the form of a self-contained repo, or a push to the cucumber-rails repo), we can pull to take a look at this.

The stacktrace does show what you're describing, but given the multitude of things interacting with each other. I want to check it's not something specific to your setup.
