### ISSUE TITLE
Cucumber marks scenario as failed even though it passed on rerun if next step following the flaky one executes "skip_this_scenario" method

### ISSUE THREAD

**Issue by eduardrudko** [cucumber/cucumber-ruby#1521]
**Describe the bug**
skip_this_scenario method makes previouse flaky step to label whole scenario thus whole run as failed instead of flaky

**To Reproduce**
1. You need to create two scenariouse like this:
```
Feature: One green and one flaky scenario

  @test
  Scenario: Green scenario
    When green step

  @test
  Scenario: Flaky scenario
    When flaky step
    Then skip scenario step
    When green step
    When green step
```
Step Definitions:

```
When(/^flaky step$/) do
  if Random.rand(10) > 5
    fail
  end
end

When(/^green step$/) do

end

When(/^skip scenario step$/) do
  skip_this_scenario
end
```

2. Run test as following: 
```
bundle exec cucumber \ 
          --retry 2 \
          --no-strict-flaky \
          --no-source \
          features/gherkin_scenarios/test_scenariou.feature
```

**Expected behavior**

The scenario is marked as flaky if flaky step failed and reran sucessfully

**Context & Motivation**

The above issue makes us think the scenario has failed and never passed but in reality it has failed and passed on rerun.

**Your Environment**
 - Cucumber 3.2.0
 - Reproduced on LINUX and Mac Big Sur. Quite less likely it has to do with the versions of those.
 - CircleCi, also reproduced locally in bare shell

**Additional context**

Run with skip_this_scenario method being executed and flaky step passed from first attempt

```
bundle exec cucumber \ 
          --retry 2 \
          --no-strict-flaky \
          --no-source \
          features/gherkin_scenarios/test_scenariou.feature

Using the default profile...
Feature: One green and one flaky scenario

  @test
  Scenario: Green scenario
    When green step

  @test
  Scenario: Flaky scenario
    When flaky step
    Then skip scenario step
    When green step
    When green step

2 scenarios (1 skipped, 1 passed)
5 steps (3 skipped, 2 passed)
0m6.540s
echo $?                                                                                                      
0 🟢 
```

Run without skip_this_scenario method being executed but flaky scenario failed and reran sucessfully.

```
bundle exec cucumber \
          --retry 2 \
          --no-strict-flaky \
          --no-source \
          features/gherkin_scenarios/test_scenariou.feature

Using the default profile...
Feature: One green and one flaky scenario

  @test
  Scenario: Green scenario
    When green step

  @test
  Scenario: Flaky scenario
    When flaky step
       (RuntimeError)
      ./features/step_definitions/general/navigation.rb:24:in `/^flaky step$/'
      features/gherkin_scenarios/test_scenariou.feature:9:in `When flaky step'

  @test
  Scenario: Flaky scenario

2 scenarios (1 flaky, 1 passed)
3 steps (1 failed, 2 passed)
0m10.917s

echo $?
0 🟢 
```

Run with skip_this_scenario method being executed and flaky step failed and reran sucessfully

```
bundle exec cucumber \
          --retry 2 \
          --no-strict-flaky \
          --no-source \
          features/gherkin_scenarios/test_scenariou.feature  

Using the default profile...
Feature: One green and one flaky scenario

  @test
  Scenario: Green scenario
    When green step

  @test
  Scenario: Flaky scenario
    When flaky step
       (RuntimeError)
      ./features/step_definitions/general/navigation.rb:24:in `/^flaky step$/'
      features/gherkin_scenarios/test_scenariou.feature:9:in `When flaky step'
    Then skip scenario step
    When green step
    When green step

  @test
  Scenario: Flaky scenario
    When flaky step
    Then skip scenario step
    When green step
    When green step

Failing Scenarios:
cucumber features/gherkin_scenarios/test_scenariou.feature:8

2 scenarios (1 failed, 1 passed)
9 steps (1 failed, 6 skipped, 2 passed)
0m10.487s
echo $?
1 🔴 

```

**Comment by aurelien-reeves** [comment]
I see that your reporting this issue for cucumber 3.2.0.

Could you please make sure this is also impacting latest cucumber 5.3.0?

**Comment by eduardrudko** [comment]
@aurelien-reeves reproduced on cucumber 5.3.0

```
bundle exec cucumber --retry 3 --no-strict-flaky --no-source features/features/test_case.feature                                                    
Feature: One green and one flaky scenario

  @test
  Scenario: Green scenario
    When green step

  @test
  Scenario: Flaky scenario
    When flaky step
       (RuntimeError)
      ./features/step_definitions/navigations.rb:5:in `/^flaky step$/'
      features/features/test_case.feature:9:in `flaky step'

  @test
  Scenario: Flaky scenario
    When flaky step
#    Then skip scenario step
#    When green step
#    When green step

2 scenarios (1 flaky, 1 passed)
3 steps (1 failed, 2 passed)
0m0.007s
┌──────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io │
│                                                                          │
│ Command line option:    --publish                                        │
│ Environment variable:   CUCUMBER_PUBLISH_ENABLED=true                    │
│ cucumber.yml:           default: --publish                               │
│                                                                          │
│ More information at https://reports.cucumber.io/docs/cucumber-ruby       │
│                                                                          │
│ To disable this message, specify CUCUMBER_PUBLISH_QUIET=true or use the  │
│ --publish-quiet option. You can also add this to your cucumber.yml:      │
│ default: --publish-quiet                                                 │
└──────────────────────────────────────────────────────────────────────────┘
echo $?                                                                                                                                             
0
```

```
bundle exec cucumber --retry 3 --no-strict-flaky --no-source features/features/test_case.feature                                                    
Feature: One green and one flaky scenario

  @test
  Scenario: Green scenario
    When green step

  @test
  Scenario: Flaky scenario
    When flaky step
       (RuntimeError)
      ./features/step_definitions/navigations.rb:5:in `/^flaky step$/'
      features/features/test_case.feature:9:in `flaky step'
    Then skip scenario step
    When green step
    When green step

  @test
  Scenario: Flaky scenario
    When flaky step
    Then skip scenario step
    When green step
    When green step

Failing Scenarios:
cucumber features/features/test_case.feature:8

2 scenarios (1 failed, 1 passed)
9 steps (1 failed, 6 skipped, 2 passed)
0m0.007s
┌──────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io │
│                                                                          │
│ Command line option:    --publish                                        │
│ Environment variable:   CUCUMBER_PUBLISH_ENABLED=true                    │
│ cucumber.yml:           default: --publish                               │
│                                                                          │
│ More information at https://reports.cucumber.io/docs/cucumber-ruby       │
│                                                                          │
│ To disable this message, specify CUCUMBER_PUBLISH_QUIET=true or use the  │
│ --publish-quiet option. You can also add this to your cucumber.yml:      │
│ default: --publish-quiet                                                 │
└──────────────────────────────────────────────────────────────────────────┘
~/RubymineProjects/untitled1 ❯ echo $?                                                                                                                                             
1
```

**Comment by mattwynne** [comment]
Wow what a crazy bug, well found @eduardrudko!

Are you interested in helping us to fix this? We'd be happy to coach you through it, or even spend time pairing with you if you're interested in becoming a contributor to Cucumber.

**Comment by eduardrudko** [comment]
@mattwynne Sure, count me in.

**Comment by mattwynne** [comment]
Awesome!

Probably the place to start is to see if we can write a full-stack test that reproduces this scenario. We might not keep this test forever (since it's quite a bizarre edge-case, and not neccearily worth documenting) but it will help us to pin down where the problem is, then perhaps we can shift to unit-testing out the bug.

You could have a look at the existing https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/cli/retry_failing_tests.feature feature and see if you can add another scenario to that one. The tricky bit is having deterministic flakeyness, but I think that problem is solved in that feature.

If you're comfortable with this, you could open a Draft pull request with that test in it, and we can move the discussion there. If anything I've suggested seems too difficult or doesn't make sense to you, just shout and we can give you the support you need. You can also find us in https://cucumber.io/community#slack in the #committers channel if you want to chat.

**Comment by eduardrudko** [comment]
@mattwynne Lovely! I going to take sometime to look at it after working hours or this weekend in worse case.

**Comment by aurelien-reeves** [comment]
cucumber@6.1.0 has a fix for this :)
