### ISSUE TITLE
Taggable Rules not working in 6.1

### ISSUE THREAD

**Issue by luke-hill** [cucumber/cucumber-ruby#1545]
**Describe the bug**
Rules cannot be tagged in 6.1

**To Reproduce**
```
@tag @tag2
Feature: Foo

  Description Here

  @rule_tag
  Rule: Default Rule
    Background:
      Given a background step

  Scenario: My Scenario
    Given a step
```
**Expected behavior**

It works

**Your Environment**
 - gherkin 18.1.1
 - cucumber 6.1.0
 - core 9.0.1
 - Ubuntu 18.04
 - Both CLI / RubyMine

**Additional context**
Stacktrace refers to UUID's not being found

```
No location found for ea3c5c3f-d060-49c3-b57f-db6e3f378b6d }. Known: ["1e2668f0-a376-4b9d-b916-2f1bb3df24b3", "85207574-3e07-4610-a8f8-87f7a1fe97f4", "b7aa1969-e3cd-41a4-81da-1e10b97dac87", "9275a077-2d2a-4527-ad15-c555831bf0af", "799fdf8b-9a03-4e9b-99e2-b24b3e0041bd", "def058f9-7df2-43c3-86bc-870db17182cd", "ad5eafc1-b5af-4572-a9ee-1fe527694fd0", "0aba4ec1-d683-4d75-9198-89c8b5cb2a3d", "8aa945a5-13a0-41e5-ad16-519ee79acd7f", "d0208907-4463-4f79-bc34-000456700d3c", "5b6c2f87-8b79-4bbf-b2ee-45f40cea9699", "17376286-9173-4f1b-bbbf-eb9b1d0bf216", "4d8d8bbd-5fb6-45aa-ab59-8655af56dbf0", "7197167f-8a88-408c-b0d4-74b2ba783e1a", "10ae1373-48ab-4ccb-b46e-2c3a75ffe992", "6f5745d9-5a0b-49dc-abb4-2df66dbbc864", "daa422c6-13ae-4445-a0f0-0acc1937cb51", "458d25e0-b0e8-4753-9ae6-f9b9429ef960", "c1cff8df-9fc4-4b98-9472-b254f9039762", "35055ceb-a9fa-4784-8d95-656b322d3a19", "1521f61d-22b2-4f5f-b516-c03a9fe593f6", "17b4d89a-b274-4ebd-9800-4a671ddb24dd", "b27058ec-37d9-4602-b2ee-0ed230e6170e", "095feb2d-d82a-493d-a5a3-7aff03ec6e80", "39ed80cd-8e8c-46f5-a965-5ae6ff005cac", "9facb718-685a-4ee1-8c7b-c660e4ee3209", "0e436415-67e3-4432-a8b5-b7a87d049a3c", "9883cb1b-ed3a-45de-bf48-ecc339619a1a", "be692e9b-10e1-4766-9f05-14bb9b566d07", "8dfc1dad-6890-4093-bdc3-5d89515aeed2", "a2abfd60-4754-4707-8d92-11f5562fcd40", "dc65478d-7bd0-458e-b73f-f287343f987b", "97da4a74-c5fb-4c26-83da-f62fccf9828e", "6b97835b-5b81-45d2-bc6c-f63786086626", "fc3053ff-45e0-4810-bbb7-3ba09098b6cd", "3263a111-3212-4c18-a927-cba4ddf25791", "3e78895b-b4a4-453e-af27-c4541e83fbe2", "34ff008c-82a3-43fa-97e3-0488c4f3476d", "def8e913-0dd3-4e37-8b7f-84de0e844ad3", "a70074f9-a649-4e7f-8219-a8f364d56670", "bd1d1626-404f-4a46-a76f-ef0d7de2a87b", "47b80c37-1f76-4023-be49-71db09b668a4", "8569ebb7-4b9a-49b3-95e1-7a1f7c699fa7", "b62cd280-c13a-40ce-9faf-f86ab43722be", "a76d1f60-4cae-4288-a23a-06c758370586", "70cd0b08-881d-4c7d-ab0a-e4f239e7e2f7", "ff0e0616-bbce-4f7b-ba7c-c86b09694842", "d6e4a4b5-6a01-49dc-a3cb-52804384d39c", "ffc31b72-c994-438a-a202-4bffa4ae7f66", "0be0898f-6be3-4fe6-b0d5-5ee7126c5dac", "6df106f2-8fe3-4ccf-a1bf-a1d4aee653cc", "3a06d020-a2af-43af-901d-6391eae9e0ed", "bb9a434d-fe23-4285-be33-c0ea3eb6b62a", "bb61f99b-7d0d-4792-b007-c81a26adf985", "915a4b31-bfa5-4887-bcf6-d7da26783dd9"] (Gherkin::AstNodeNotLocatedException)
/home/luke/.rvm/gems/ruby-2.7.2/gems/cucumber-gherkin-18.1.1/lib/gherkin/query.rb:13:in `location'
/home/luke/.rvm/gems/ruby-2.7.2/gems/cucumber-core-9.0.1/lib/cucumber/core/compiler.rb:87:in `source_line'
/home/luke/.rvm/gems/ruby-2.7.2/gems/cucumber-core-9.0.1/lib/cucumber/core/compiler.rb:83:in `source_line_for_pickle_tag'
/home/luke/.rvm/gems/ruby-2.7.2/gems/cucumber-core-9.0.1/lib/cucumber/core/compiler.rb:41:in `block in create_test_case'
/home/luke/.rvm/gems/ruby-2.7.2/gems/cucumber-core-9.0.1/lib/cucumber/core/compiler.rb:41:in `map'
/home/luke/.rvm/gems/ruby-2.7.2/gems/cucumber-core-9.0.1/lib/cucumber/core/compiler.rb:41:in `create_test_case'
/home/luke/.rvm/gems/ruby-2.7.2/gems/cucumber-core-9.0.1/lib/cucumber/core/compiler.rb:26:in `pickle'
/home/luke/.rvm/gems/ruby-2.7.2/gems/cucumber-core-9.0.1/lib/cucumber/core/gherkin/parser.rb:27:in `block in docum
```

**Comment by aurelien-reeves** [comment]
Fixed with incoming v7.0
Verified here: https://github.com/cucumber/cucumber-ruby/pull/1549
The fix itself has been done in cucumber-gherkin which has been updated here: https://github.com/cucumber/cucumber-ruby/pull/1544
