### ISSUE TITLE
Cucumber terminating with `negative argument` while trying to process a failing background step with a table

### ISSUE THREAD

**Issue by JoeSSS** [cucumber/cucumber-ruby#1546]
**Describe the bug**
The bug is quite confusing but I will try my best to describe it.

When running a test with a background with a table like:

```
Background:
    Given user creates a group with the following properties:
      | group_name | Group name - [% Time.now %]  |
      | group_type   | SampleGroup                               |
```
the first test in the feature file runs fine. But the 2nd will fail in this case because it seems like `Time.now` will be the same for both test executions and the test won't be able to create duplicates (which I'm not sure is an expected behavior either). As soon as the 2nd scenario will fail, the run will be immediately terminated with the stack trace shared below, and the Cucumber will "crash" and not finish gracefully (no reports or meaningful error message).

**Expected behavior**
The test is terminated with a proper error.

**Context & Motivation**

The issue is not easy to reproduce, but when it happens it is quite bad since the whole run is terminating and a re-run will see 0 tests and will finish as a success. So we basically had the problem for quite a while without knowing we have failing tests.

**Stacktrace**
```
negative argument (ArgumentError)
/Users/joes/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.3.2/lib/active_support/core_ext/string/indent.rb:10:in `*'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.3.2/lib/active_support/core_ext/string/indent.rb:10:in `indent!'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.3.2/lib/active_support/core_ext/string/indent.rb:43:in `block in indent'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.3.2/lib/active_support/core_ext/string/indent.rb:43:in `tap'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/activesupport-6.1.3.2/lib/active_support/core_ext/string/indent.rb:43:in `indent'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/formatter/console.rb:37:in `format_step'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/formatter/pretty.rb:341:in `print_step_data'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/formatter/pretty.rb:115:in `on_test_step_finished'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/event_bus.rb:34:in `block in broadcast'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/event_bus.rb:34:in `each'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/event_bus.rb:34:in `broadcast'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/event_bus.rb:40:in `method_missing'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/runner.rb:37:in `around_hook'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/around_hook.rb:12:in `describe_to'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/case.rb:80:in `block (2 levels) in compose_around_hooks'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/case.rb:81:in `compose_around_hooks'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/case.rb:29:in `block in describe_to'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/runner.rb:19:in `test_case'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/filter.rb:57:in `test_case'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/filters/retry.rb:18:in `test_case'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/filters/quit.rb:11:in `test_case'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:21:in `block in done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `map'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/filter.rb:62:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/filter.rb:62:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/filter.rb:62:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/filter.rb:62:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/filter.rb:62:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/filter.rb:62:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/filters/locations_filter.rb:20:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/filter.rb:62:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/compiler.rb:31:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core/gherkin/parser.rb:46:in `done'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core.rb:35:in `parse'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-core-9.0.1/lib/cucumber/core.rb:24:in `compile'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/runtime.rb:79:in `run!'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/lib/cucumber/cli/main.rb:29:in `execute!'
/Users/joes/.rvm/gems/ruby-2.7.1/gems/cucumber-6.1.0/bin/cucumber:9:in `<top (required)>'
/Users/joes/.rvm/gems/ruby-2.7.1/bin/cucumber:23:in `load'
/Users/joes/.rvm/gems/ruby-2.7.1/bin/cucumber:23:in `<main>'
/Users/joes/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
/Users/joes/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'
Terminated
```

**Your Environment**
 - Versions used 6.1.0 (more version info is seen in the stack trace)
 - Operating System: both MacOS and Linux

**Additional context**
Seems to be related to https://github.com/cucumber/cucumber-ruby/issues/620

**Comment by aurelien-reeves** [comment]
Thanks for the report.
How looks your corresponding step definition?
How do you replace `Time.now`?

I am pretty new to cucumber. I never see that `[% %]`. Is this something built-in into cucumber/gherkin? Or something you are using yourself as some kind of templating like erb?

**Comment by JoeSSS** [comment]
This is something we use for templating. I tried to remove the [% things and still getting the same result. It feels to me that it is because we are doing operations on these objects passed in the Background, but somehow they are shared with the next test, which I personally do not expect

**Comment by aurelien-reeves** [comment]
Thanks for the clarification 👍

**Comment by mattwynne** [comment]
Seems to me it might be a clash with ActiveSupport's `String#indent` method and [this monkey patch](https://github.com/cucumber/cucumber-ruby/blob/main/lib/cucumber/core_ext/string.rb) of our own.

I suggest that the fix would be to remove our monkey patch on `String` and make that method a static/helper method somewhere, e.g. on `Cucumber::Formatter::Console`

@JoeSSS would you be interested in attempting a PR for that? We can give you all the support you need.

**Comment by JoeSSS** [comment]
@mattwynne I tried removing the patch but it did not help. I tried to reproduce the issue and create a sample project with it for a couple of hours but couldn't find any common sense in the way the issue reproduces.. For the moment I fixed it just by moving the background to each step and removing the background section.

What I see when trying to reproduce is that even making the step and step definition shorter helps to stop getting the issue. But also this steps does a couple of API calls and remembers their answers and if I just stop doing one of the calls, the issues disappear again. So it looks like something is just overflows and I do not understand what. For me, the main suspicion is still the fact that variables are shared between the tests with background, I tried to print the Time.now that we pass from the table and both tests have given me the same results

```
 Background:                                                                             # features/Test.feature:4
Group 2021-05-28 20:18:06 +0200
    Given with the following properties via API: # features/step_definitions/test_steps.rb:1
      | group_name | Group [% Time.now %]                                                        |

  Scenario: In a group detail view, scroll the posts list until it loads more posts # features/Test.feature:15
Group 2021-05-28 20:18:06 +0200
```

**Comment by mattwynne** [comment]
I don't think it's a matter of just removing the monkey patch. The problem you're experiencing I think, like in #620, that you're getting ActiveSupport's version of `String#indent` instead of ours. So removing ours won't make any difference.

**Comment by mattwynne** [comment]
What we need to do is _move_ ours (but still use it) so they don't get mixed up with each other.

**Comment by JoeSSS** [comment]
Ah, I misinterpreted your last message :) I will try to make a PR

**Comment by mattwynne** [comment]
Fantastic! Just let us know if you need any help.

**Comment by JoeSSS** [comment]
I created a "dirty" fix https://github.com/cucumber/cucumber-ruby/pull/1548, it solves the issue. I will take a look later how to make it better

**Comment by aurelien-reeves** [comment]
@JoeSSS did #1548 fixed this issue? If so, can we close it? Or is there some remaining bug?

**Comment by JoeSSS** [comment]
ah, sure weird that it wasn't automatically closed

**Comment by luke-hill** [comment]
Note to others visiting this. There are also other bugs present in v5.3 that relate to this (Core methods / requires failing), the solution is just upgrading to remove the AS dependency
