### ISSUE TITLE
Both Doc String and Data Table in a Step?

### ISSUE THREAD

**Issue by pgundlupetvenkatesh** [cucumber/cucumber-ruby#1717]
### 🤔 What's the problem you're trying to solve?

Can a Step have both Doc String and Data Table?
I am working on a data table step which is getting bigger and I want to use Doc String to cut it short.

example.feature
```gherkin
And I should see a message for following questions:
      | que |
      | 2     |
      | 6     |
    """
    current versions of Cucumber support content types as the delimiter.
    """
```
example_steps.rb
```ruby
When("I should see a message for following questions:") do | *table, message |
  ...
end
```
I get this error when I run this feature
```bash
features/example.feature: expected: #EOF, #TableRow, #StepLine, #TagLine, #ExamplesLine, #ScenarioLine, #RuleLine, #Comment, #Empty, got '"""' (Cucumber::Core::Gherkin::ParseError)
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-core-11.0.0/lib/cucumber/core/gherkin/parser.rb:29:in `block in document'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:64:in `yield'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:64:in `block in yield_parse_errors'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:53:in `each'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:53:in `yield_parse_errors'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:42:in `rescue in block (2 levels) in messages'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:27:in `block (2 levels) in messages'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:79:in `yield'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:79:in `block (2 levels) in sources'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:78:in `each'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:78:in `block in sources'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:25:in `each'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:25:in `each'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-gherkin-23.0.1/lib/gherkin/stream/parser_message_stream.rb:25:in `block in messages'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-core-11.0.0/lib/cucumber/core/gherkin/parser.rb:21:in `each'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-core-11.0.0/lib/cucumber/core/gherkin/parser.rb:21:in `each'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-core-11.0.0/lib/cucumber/core/gherkin/parser.rb:21:in `document'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-core-11.0.0/lib/cucumber/core.rb:33:in `block in parse'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-core-11.0.0/lib/cucumber/core.rb:32:in `each'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-core-11.0.0/lib/cucumber/core.rb:32:in `parse'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-core-11.0.0/lib/cucumber/core.rb:24:in `compile'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-8.0.0/lib/cucumber/runtime.rb:81:in `run!'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-8.0.0/lib/cucumber/cli/main.rb:29:in `execute!'
C:/<path>/lib/ruby/gems/3.2.0/gems/cucumber-8.0.0/bin/cucumber:9:in `<top (required)>'
C:/<path>/bin/cucumber:32:in `load'
C:/<path>/bin/cucumber:32:in `<main>'
```

### ⛏ Have you considered any alternatives or workarounds?

I am not sure about any workarounds

### 📚 Any additional context?

Ruby v3.2.0
Cucumber v8

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by luke-hill** [comment]
This is a really GOOD question and one that should be asked / satisfied at a gherkin level / common level.

Obviously based on the error the answer initially seems to be no.

Thoughts @mattwynne / @mpkorstanje / @ehuelsmann / @davidjgoss

**Comment by mattwynne** [comment]
This isn't currently supported.

A workaround would be to use two separate steps to capture this data from the scenario.

**Comment by jenisys** [comment]
@pgundlupetvenkatesh 
* Both DocString and DataTable for a step makes no sense for me (and is chaotic, not really readable)
* Either providing a `DocString` or a `DataTable` for a step may make sometimes sense.
  The step implementation must support this. In this case, it can handle/process raw data as string. As alternative, it will also support structured-data provided by a DataTable.
* Often, you are better served if you split-up the functionality/step-wording into two steps, one that supports the `DocString` and another step that supports the `DataTable`
