### ISSUE TITLE
undefined method `map' for nil:NilClass (NoMethodError) with latest 1.2.4 gem

### ISSUE THREAD

**Issue by bradley-s** [cucumber/cucumber-ruby#426]
```
undefined method `map' for nil:NilClass (NoMethodError)
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/scenario_outline.rb:109:in `examples_array'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/scenario_outline.rb:74:in `each_example_row'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/scenario_outline.rb:49:in `to_units'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/feature.rb:92:in `units'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/feature.rb:91:in `map'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/feature.rb:91:in `units'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/feature.rb:27:in `step_count'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/features.rb:34:in `step_count'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/gherkin-2.11.7/lib/gherkin/tag_expression.rb:30:in `inject'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/features.rb:34:in `each'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/features.rb:34:in `inject'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/features.rb:34:in `step_count'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/formatter/html.rb:45:in `before_features'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/tree_walker.rb:181:in `__send__'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/tree_walker.rb:181:in `send_to_all'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/tree_walker.rb:179:in `each'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/tree_walker.rb:179:in `send_to_all'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/tree_walker.rb:169:in `broadcast'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/ast/tree_walker.rb:20:in `visit_features'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/runtime.rb:48:in `run!'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/cli/main.rb:43:in `execute!'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/../lib/cucumber/cli/main.rb:20:in `execute'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/gems/cucumber-1.2.4/bin/cucumber:14
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/bin/cucumber:19:in `load'
/Users/ci/hudsonCI/workspace/test_regression/bundle/ruby/1.8/bin/cucumber:19
```

**Comment by ZakMiller** [comment]
I experienced this issue when I had a "@" for a tag but no text after.
