### ISSUE TITLE
"WARNING: cannot load such file -- 2.0/gherkin_lexer_en" error message on Windows

### ISSUE THREAD

**Issue by zeljkofilipin** [cucumber/cucumber-ruby#500]
Cucumber works fine on Windows+Ruby 1.9 combination:

```
A:\>ruby -v
ruby 1.9.3p448 (2013-06-27) [i386-mingw32]

A:\>cucumber
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
Using the default profile...
...
```

It works just fine on Mac+Ruby 2.0 combination:

```
$ ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.4.0]

$ cucumber
Using the default profile...
...
```

But it refuses to work on Windows+Ruby 2.0 combination:

```
﻿A:\>ruby -v
ruby 2.0.0p247 (2013-06-27) [i386-mingw32]

A:\>cucumber
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
WARNING: cannot load such file -- 2.0/gherkin_lexer_en
Couldn't load 2.0/gherkin_lexer_en
The $LOAD_PATH was:
C:/Ruby200/lib/ruby/gems/2.0.0/gems/syntax-1.0.0/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/rspec-expectations-2.13.0/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/parallel_tests-0.15.0/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/parallel-0.7.1/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/page-object-0.9.0/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/watir-webdriver-0.6.4/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.33.0/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/websocket-1.0.7/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/rubyzip-0.9.9/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/page_navigation-0.9/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/net-http-persistent-2.8/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/json-1.8.0/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/data_magic-0.14/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/yml_reader-0.2/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/faker-1.1.2/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/i18n-0.6.4/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.2/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/gherkin-2.12.0-x86-mingw32/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/multi_json-1.7.7/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/diff-lcs-1.2.4/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/chunky_png-1.2.8/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/childprocess-0.3.9/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/ffi-1.9.0-x86-mingw32/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/ffi-1.9.0-x86-mingw32/ext/ffi_c
C:/Ruby200/lib/ruby/gems/2.0.0/gems/builder-3.2.2/lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.1.0/lib
lib
C:/Ruby200/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib
C:/Ruby200/lib/ruby/site_ruby/2.0.0
C:/Ruby200/lib/ruby/site_ruby/2.0.0/i386-msvcrt
C:/Ruby200/lib/ruby/site_ruby
C:/Ruby200/lib/ruby/vendor_ruby/2.0.0
C:/Ruby200/lib/ruby/vendor_ruby/2.0.0/i386-msvcrt
C:/Ruby200/lib/ruby/vendor_ruby
C:/Ruby200/lib/ruby/2.0.0
C:/Ruby200/lib/ruby/2.0.0/i386-mingw32. Reverting to Ruby lexer.
No lexer was found for en (cannot load such file -- gherkin/lexer/en). Supported languages are listed in gherkin/i18n.json. (Gherkin::I18n::LexerNotFound)
C:/Ruby200/lib/ruby/gems/2.0.0/gems/gherkin-2.12.0-x86-mingw32/lib/gherkin/i18n.rb:108:in `rescue in lexer'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/gherkin-2.12.0-x86-mingw32/lib/gherkin/i18n.rb:97:in `lexer'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/gherkin-2.12.0-x86-mingw32/lib/gherkin/parser/parser.rb:139:in `transition_table'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/gherkin-2.12.0-x86-mingw32/lib/gherkin/parser/parser.rb:128:in `build_transition_map'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/gherkin-2.12.0-x86-mingw32/lib/gherkin/parser/parser.rb:124:in `transition_map'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/gherkin-2.12.0-x86-mingw32/lib/gherkin/parser/parser.rb:91:in `initialize'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/gherkin-2.12.0-x86-mingw32/lib/gherkin/parser/parser.rb:68:in `new'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/gherkin-2.12.0-x86-mingw32/lib/gherkin/parser/parser.rb:68:in `push_machine'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/gherkin-2.12.0-x86-mingw32/lib/gherkin/parser/parser.rb:31:in `parse'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.2/lib/cucumber/feature_file.rb:37:in `parse'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.2/lib/cucumber/runtime/features_loader.rb:28:in `block in load'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.2/lib/cucumber/runtime/features_loader.rb:26:in `each'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.2/lib/cucumber/runtime/features_loader.rb:26:in `load'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.2/lib/cucumber/runtime/features_loader.rb:14:in `features'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.2/lib/cucumber/runtime.rb:178:in `features'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.2/lib/cucumber/runtime.rb:48:in `run!'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.2/lib/cucumber/cli/main.rb:47:in `execute!'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-1.3.2/bin/cucumber:13:in `<top (required)>'
C:/Ruby200/bin/cucumber:23:in `load'
C:/Ruby200/bin/cucumber:23:in `<main>'
```

**Comment by fakeleft** [comment]
The correct related issue is [259](https://github.com/cucumber-attic/gherkin/issues/259), not 257.
