### ISSUE TITLE
Too many open files - getcwd (Errno::EMFILE)

### ISSUE THREAD

**Issue by samfrench** [cucumber/cucumber-ruby#668]
Getting an error about too many open files:

```
Too many open files - getcwd (Errno::EMFILE)
/Users/matt/.gem/ruby/2.0.0/gems/multi_test-0.1.1/lib/multi_test/assertion_library.rb:32:in `require'
/Users/matt/.gem/ruby/2.0.0/gems/multi_test-0.1.1/lib/multi_test/assertion_library.rb:32:in `block in available'
/Users/matt/.gem/ruby/2.0.0/gems/multi_test-0.1.1/lib/multi_test/assertion_library.rb:16:in `call'
/Users/matt/.gem/ruby/2.0.0/gems/multi_test-0.1.1/lib/multi_test/assertion_library.rb:16:in `require?'
/Users/matt/.gem/ruby/2.0.0/gems/multi_test-0.1.1/lib/multi_test/assertion_library.rb:6:in `each'
/Users/matt/.gem/ruby/2.0.0/gems/multi_test-0.1.1/lib/multi_test/assertion_library.rb:6:in `detect'
/Users/matt/.gem/ruby/2.0.0/gems/multi_test-0.1.1/lib/multi_test/assertion_library.rb:6:in `detect_best'
/Users/matt/.gem/ruby/2.0.0/gems/multi_test-0.1.1/lib/multi_test.rb:31:in `extend_with_best_assertion_library'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/rb_support/rb_language.rb:121:in `extend_world'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/rb_support/rb_language.rb:67:in `begin_rb_scenario'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/rb_support/rb_language.rb:101:in `begin_scenario'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/language_support/language_methods.rb:14:in `before'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime/support_code.rb:112:in `block in fire_hook'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime/support_code.rb:111:in `each'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime/support_code.rb:111:in `fire_hook'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime.rb:107:in `before'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime.rb:98:in `before_and_after'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime.rb:82:in `block in with_hooks'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime/support_code.rb:120:in `call'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime/support_code.rb:120:in `block (3 levels) in around'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/language_support/language_methods.rb:9:in `block in around'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/language_support/language_methods.rb:97:in `call'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/language_support/language_methods.rb:97:in `execute_around'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/language_support/language_methods.rb:8:in `around'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime/support_code.rb:119:in `block (2 levels) in around'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime/support_code.rb:123:in `call'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime/support_code.rb:123:in `around'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime.rb:94:in `around'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime.rb:81:in `with_hooks'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/tree_walker.rb:13:in `execute'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/scenario.rb:32:in `block in accept'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/scenario.rb:79:in `with_visitor'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/scenario.rb:31:in `accept'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/tree_walker.rb:58:in `block in visit_feature_element'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/tree_walker.rb:57:in `visit_feature_element'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/feature.rb:38:in `block in accept'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/feature.rb:37:in `each'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/feature.rb:37:in `accept'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/tree_walker.rb:27:in `block in visit_feature'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/tree_walker.rb:26:in `visit_feature'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/features.rb:28:in `block in accept'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/features.rb:17:in `each'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/features.rb:17:in `each'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/features.rb:27:in `accept'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/tree_walker.rb:21:in `block in visit_features'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/ast/tree_walker.rb:20:in `visit_features'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/runtime.rb:49:in `run!'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/matt/.gem/ruby/2.0.0/gems/cucumber-1.3.12/bin/cucumber:13:in `<top (required)>'
/Users/matt/.gem/ruby/2.0.0/bin/cucumber:23:in `load'
/Users/matt/.gem/ruby/2.0.0/bin/cucumber:23:in `<main>'
```

This the Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    active_support (3.0.0)
      activesupport (= 3.0.0)
    activesupport (3.0.0)
    addressable (2.3.6)
    anmo (0.0.30)
      dalli
      httparty
      rack
      thin
    awesome_print (1.2.0)
    builder (3.2.2)
    capybara (2.1.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-mechanize (1.1.0)
      capybara (~> 2.1.0)
      mechanize (~> 2.7)
    childprocess (0.5.2)
      ffi (~> 1.0, >= 1.0.11)
    chunky_png (1.3.0)
    cliver (0.3.2)
    coderay (1.1.0)
    cucumber (1.3.14)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.3)
      gherkin (~> 2.12)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.1)
    daemons (1.1.9)
    dalli (2.7.0)
    diff-lcs (1.2.5)
    domain_name (0.5.18)
      unf (>= 0.0.5, < 1.0.0)
    eventmachine (1.0.3)
    exifr (1.1.3)
    ffi (1.9.3)
    fspath (2.1.0)
    gherkin (2.12.2)
      multi_json (~> 1.3)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    httparty (0.13.1)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.6.9)
    image_optim (0.13.1)
      exifr (~> 1.1.3)
      fspath (~> 2.1.0)
      image_size (~> 1.3.0)
      in_threads (~> 1.2.0)
      progress (~> 3.0.0)
    image_size (1.3.0)
    in_threads (1.2.1)
    iniparse (1.3.2)
    json (1.8.1)
    mechanize (2.7.3)
      domain_name (~> 0.5, >= 0.5.1)
      http-cookie (~> 1.0)
      mime-types (~> 2.0)
      net-http-digest_auth (~> 1.1, >= 1.1.1)
      net-http-persistent (~> 2.5, >= 2.5.2)
      nokogiri (~> 1.4)
      ntlm-http (~> 0.1, >= 0.1.1)
      webrobots (>= 0.0.9, < 0.2)
    method_source (0.8.2)
    mime-types (2.2)
    mini_portile (0.5.3)
    multi_json (1.9.2)
    multi_test (0.1.1)
    multi_xml (0.5.5)
    net-http-digest_auth (1.4)
    net-http-persistent (2.9.4)
    net-ssh (2.8.0)
    nokogiri (1.6.1)
      mini_portile (~> 0.5.0)
    ntlm-http (0.1.1)
    poltergeist (1.5.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    progress (3.0.0)
    pry (0.9.12.6)
      coderay (~> 1.0)
      method_source (~> 0.8)
      slop (~> 3.4)
    rack (1.5.2)
    rack-test (0.6.2)
      rack (>= 1.0)
    rake (10.3.0)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.8)
    rspec-expectations (2.14.5)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.14.6)
    rubyzip (1.1.3)
    sass (3.3.0)
      rake
    selenium-webdriver (2.41.0)
      childprocess (>= 0.5.0)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0.4)
    slop (3.5.0)
    thin (1.6.2)
      daemons (>= 1.0.9)
      eventmachine (>= 1.0.0)
      rack (>= 1.0.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.6)
    webrobots (0.1.1)
    websocket (1.0.7)
    websocket-driver (0.3.2)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_support
  addressable
  anmo
  awesome_print
  capybara (~> 2.1.0)
  capybara-mechanize
  chunky_png
  cucumber
  httparty
  i18n
  image_optim
  iniparse
  json
  net-ssh
  nokogiri
  poltergeist
  pry
  rake
  rest-client
  rspec
  sass (= 3.3.0)
  selenium-webdriver
```

When the cucumbers worked previously, this is our Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    active_support (3.0.0)
      activesupport (= 3.0.0)
    activesupport (3.0.0)
    addressable (2.3.5)
    anmo (0.0.30)
      dalli
      httparty
      rack
      thin
    awesome_print (1.2.0)
    builder (3.2.2)
    capybara (2.1.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-mechanize (1.1.0)
      capybara (~> 2.1.0)
      mechanize (~> 2.7)
    childprocess (0.5.1)
      ffi (~> 1.0, >= 1.0.11)
    chunky_png (1.3.0)
    cliver (0.3.2)
    coderay (1.1.0)
    cucumber (1.3.12)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.3)
      gherkin (~> 2.12)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.1)
    daemons (1.1.9)
    dalli (2.7.0)
    diff-lcs (1.2.5)
    domain_name (0.5.16)
      unf (>= 0.0.5, < 1.0.0)
    eventmachine (1.0.3)
    exifr (1.1.3)
    ffi (1.9.3)
    fspath (2.1.0)
    gherkin (2.12.2)
      multi_json (~> 1.3)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    httparty (0.13.0)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.6.9)
    image_optim (0.12.1)
      exifr (~> 1.1.3)
      fspath (~> 2.1.0)
      image_size (~> 1.2.0)
      in_threads (~> 1.2.0)
      progress (~> 3.0.0)
    image_size (1.2.0)
    in_threads (1.2.0)
    iniparse (1.1.6)
    json (1.8.1)
    mechanize (2.7.3)
      domain_name (~> 0.5, >= 0.5.1)
      http-cookie (~> 1.0)
      mime-types (~> 2.0)
      net-http-digest_auth (~> 1.1, >= 1.1.1)
      net-http-persistent (~> 2.5, >= 2.5.2)
      nokogiri (~> 1.4)
      ntlm-http (~> 0.1, >= 0.1.1)
      webrobots (>= 0.0.9, < 0.2)
    method_source (0.8.2)
    mime-types (2.2)
    mini_portile (0.5.2)
    multi_json (1.9.0)
    multi_test (0.1.1)
    multi_xml (0.5.5)
    net-http-digest_auth (1.4)
    net-http-persistent (2.9.4)
    net-ssh (2.8.0)
    nokogiri (1.6.1)
      mini_portile (~> 0.5.0)
    ntlm-http (0.1.1)
    poltergeist (1.5.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    progress (3.0.0)
    pry (0.9.12.6)
      coderay (~> 1.0)
      method_source (~> 0.8)
      slop (~> 3.4)
    rack (1.5.2)
    rack-test (0.6.2)
      rack (>= 1.0)
    rake (10.1.1)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.8)
    rspec-expectations (2.14.5)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.14.6)
    rubyzip (1.1.1)
    sass (3.3.0)
      rake
    selenium-webdriver (2.40.0)
      childprocess (>= 0.5.0)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0.4)
    slop (3.5.0)
    thin (1.6.2)
      daemons (>= 1.0.9)
      eventmachine (>= 1.0.0)
      rack (>= 1.0.0)
    unf (0.1.3)
      unf_ext
    unf_ext (0.0.6)
    webrobots (0.1.1)
    websocket (1.0.7)
    websocket-driver (0.3.2)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_support
  addressable
  anmo
  awesome_print
  capybara (~> 2.1.0)
  capybara-mechanize
  chunky_png
  cucumber
  httparty
  i18n
  image_optim
  iniparse
  json
  net-ssh
  nokogiri
  poltergeist
  pry
  rake
  rest-client
  rspec
  sass (= 3.3.0)
  selenium-webdriver
```

**Comment by Pysis868** [comment]
Clicking that link for issue cucumber/#667 results in a 404.
Incidentally, #667 to this repo does bring a related issue.

**Comment by mattwynne** [comment]
Yes, this repo has been renamed from cucumber to cucumber-ruby in the mean-time.
