### ISSUE TITLE
cannot load such file -- cucumber/ast/scenario (LoadError) with cucumber 2.0 beta 3

### ISSUE THREAD

**Issue by anilreddy** [cucumber/cucumber-ruby#744]
Hi,

I am getting the below error while executing watir-cucumber scripts using cucumber 2.0 beta 3 in windows.

``` Batchfile
cannot load such file -- cucumber/ast/scenario (LoadError)
Y:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:116:in `require'
Y:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:116:in `rescue in require'
Y:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:122:in `require'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/pretty_face-0.9.1/lib/pretty_face/formatter/html.rb:5:in `<top (required)>'
Y:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:64:in `require'
Y:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:64:in `require'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/pretty_face-0.9.1/lib/pretty_face.rb:2:in `<top (required)>'
Y:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:116:in `require'
Y:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:116:in `rescue in require'
Y:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:122:in `require'
Y:/XPRK177/Watir Scripts/BTP/cucumber/features/support/env.rb:7:in `<top (required)>'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.3/lib/cucumber/rb_support/rb_language.rb:94:in `load'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.3/lib/cucumber/rb_support/rb_language.rb:94:in `load_code_file'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.3/lib/cucumber/runtime/support_code.rb:172:in `load_file'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.3/lib/cucumber/runtime/support_code.rb:85:in `block in load_files!'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.3/lib/cucumber/runtime/support_code.rb:84:in `each'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.3/lib/cucumber/runtime/support_code.rb:84:in `load_files!'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.3/lib/cucumber/runtime.rb:298:in `load_step_definitions'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.3/lib/cucumber/runtime.rb:67:in `run!'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.3/lib/cucumber/cli/main.rb:38:in `execute!'
Y:/Ruby200/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.beta.3/bin/cucumber:9:in `<top (required)>'
Y:/Ruby200/bin/cucumber:23:in `load'
Y:/Ruby200/bin/cucumber:23:in `<main>'
```

let me know if you need more info

Thanks,
Anil

**Comment by Githraine** [comment]
Does anyone know of an update on this issue?
Mattwynne, that solution just led to different errors.
Does anyone have a workaround?  What version on Cucumber works with the latest pretty_face?

**Comment by mattwynne** [comment]
Having looked at the PrettyFace code, it's going to need quite a few changes to support Cucumber 2.0.

**Comment by avinash530** [comment]
Even I faced the same. I downgraded cucumber version and continued. Awaiting fix from Pretty Face
