### ISSUE TITLE
undefined method `map' for nil:NilClass (NoMethodError) in "print_snippets"

### ISSUE THREAD

**Issue by dg-ratiodata** [cucumber/cucumber-ruby#831]
Hi @mattwynne,

I got another error. An instance variable seems to be nil where it should not be nil.

```bash
% bundle exec cucumber --format stepdefs | grep stdin
0.0000000 /^I close the stdin stream$/                                         # aruba-0.6.2/lib/aruba/cucumber.rb:121
undefined method `map' for nil:NilClass (NoMethodError)
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/formatter/console.rb:150:in `print_snippets'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/formatter/progress.rb:83:in `print_summary'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/formatter/usage.rb:69:in `print_summary'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/formatter/progress.rb:25:in `after_features'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/adapter.rb:110:in `after'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/adapter.rb:46:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:35:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/filter.rb:61:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/filter.rb:61:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/filter.rb:61:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/filter.rb:61:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/filter.rb:61:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/filter.rb:61:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/filters/quit.rb:17:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/test/filters/locations_filter.rb:19:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/filter.rb:61:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/filters/gated_receiver.rb:19:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/filters/tag_limits.rb:29:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/compiler.rb:23:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core/gherkin/parser.rb:31:in `done'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core.rb:29:in `parse'
/home/user/.gem/ruby/2.2.1/gems/cucumber-core-1.1.3/lib/cucumber/core.rb:18:in `compile'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:70:in `run!'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb:38:in `execute!'
/home/user/.gem/ruby/2.2.1/gems/cucumber-2.0.0/bin/cucumber:9:in `<top (required)>'
/home/user/.gem/ruby/2.2.1/bin/cucumber:23:in `load'
/home/user/.gem/ruby/2.2.1/bin/cucumber:23:in `<main>'
```

**Comment by mattwynne** [comment]
Thanks for reporting @dg-ratiodata. I can't reproduce this. Are you running this command against the master branch of aruba, or something else?

**Comment by dg-ratiodata** [comment]
Puh... I think, no it should be the latest gem version 0.6.2. But I'm not sure anymore which project it was where the error was raised. Damn...

I tried cucumber#master and aruba#master as well in two projects I worked on yesterday. I cannot reproduce the error. Weird...

Does it make sense to add `Array(@snippets_input)` just to be sure that the input is an array? But maybe that hides the real cause for the error.

**Comment by mattwynne** [comment]
When I looked at the code, I could see that variable being set to `[]` in the constructor of the `Progress` formatter, so that should be unnecessary.

I anticipate this code going away over the next few releases as we re-write formatters against the new API, so I'm not too precious about it.
