### ISSUE TITLE
cucumber --i18n <invalid_language> breaks

### ISSUE THREAD

**Issue by tejasbubane** [cucumber/cucumber-ruby#869]
When I run `cucumber --i18n ja`, I get the proper japanese output.
But when I drop an invalid language it breaks:

```
tech-6@batman:~/calculator|⇒  cucumber --i18n ma
undefined method `[]' for nil:NilClass (NoMethodError)
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/gherkin-2.12.2/lib/gherkin/i18n.rb:93:in `initialize'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/gherkin-2.12.2/lib/gherkin/i18n.rb:25:in `new'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/gherkin-2.12.2/lib/gherkin/i18n.rb:25:in `get'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/cucumber-2.0.0/lib/cucumber/cli/options.rb:374:in `list_keywords_and_exit'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/cucumber-2.0.0/lib/cucumber/cli/options.rb:122:in `block (2 levels) in parse!'
/home/tech-6/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1396:in `call'
/home/tech-6/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1396:in `block in parse_in_order'
/home/tech-6/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
/home/tech-6/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
/home/tech-6/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
/home/tech-6/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
/home/tech-6/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/cucumber-2.0.0/lib/cucumber/cli/options.rb:253:in `parse!'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/cucumber-2.0.0/lib/cucumber/cli/configuration.rb:25:in `parse!'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb:64:in `block in configuration'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb:63:in `tap'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb:63:in `configuration'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb:35:in `execute!'
/home/tech-6/.rvm/gems/ruby-2.2.2/gems/cucumber-2.0.0/bin/cucumber:9:in `<top (required)>'
/home/tech-6/.rvm/gems/ruby-2.2.2/bin/cucumber:23:in `load'
/home/tech-6/.rvm/gems/ruby-2.2.2/bin/cucumber:23:in `<main>'
/home/tech-6/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/home/tech-6/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

I think this should be handled properly, maybe telling that the language is not available or even giving the list of available languages.

**Comment by mattwynne** [comment]
Thanks for reporting. If you'd like to help us with a fix we can support you with TDD'ing it.

**Comment by mattwynne** [comment]
Thanks @danascheider :smile:
