### ISSUE TITLE
cucumber 2.0.0 -> 2.0.1 breaks fivemat

### ISSUE THREAD

**Issue by limhoff-r7** [cucumber/cucumber-ruby#893]
One of our [builds](https://travis-ci.org/rapid7/metasploit-cache/jobs/71104061) saw the upgrade to cucumber 2.0.1 because we were pinning with `~> 2.0`, assuming semantic versioning, but 2.0.1 gives this error:

```
undefined method `divmod' for #<Cucumber::Formatter::LegacyApi::Ast::Features:0x00000004a3eb30> (NoMethodError)
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/duration.rb:8:in `format_duration'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/console.rb:87:in `print_stats'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/fivemat-1.3.1/lib/fivemat/cucumber.rb:34:in `after_features'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/legacy_api/adapter.rb:111:in `after'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/legacy_api/adapter.rb:47:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/fanout.rb:15:in `each'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/runner.rb:35:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/filters/quit.rb:17:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/filters/locations_filter.rb:19:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/compiler.rb:23:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/gherkin/parser.rb:31:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core.rb:29:in `parse'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core.rb:18:in `compile'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/runtime.rb:70:in `run!'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/cli/main.rb:38:in `execute!'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/bin/cucumber:9:in `<top (required)>'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/bin/cucumber:23:in `load'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/bin/cucumber:23:in `<main>'
```

If I downgrade to cucumber 2.0.0 by changing the `~> 2.0` in the `Gemfile` to `2.0.0`, it [works](https://travis-ci.org/rapid7/metasploit-cache/jobs/71110968).

# Summary

| gem           | broke | works |
|---------------|-------|-------|
| cucumber      | 2.0.1 | 2.0.0 |
| cucumber-core | 1.2.0 | 1.1.3 |
| fivemat       | 1.3.1 | 1.3.1 |

**Comment by brasmusson** [comment]
It was not the intention to break anything, but unfortunately I forgot that the public methods of `Cucumber::Formatter::Console` must be considered a public API when I was rewriting formatters for the new formatter API. The old formatter API that fivemat uses will be removed, but not until v3.0 as the current plan stands, see #839.
