### ISSUE TITLE
CLI confusing ruby and cukes flags

### ISSUE THREAD

**Issue by jonasschneider** [cucumber/cucumber-ruby#921]
I'm trying to run this:

    $ /Users/jonas/.rbenv/versions/2.1.5/bin/ruby -S bundle exec cucumber -w -t @wip
    You can't use both --strict and --wip (RuntimeError)
    /Users/jonas/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-2.1.0/lib/cucumber/cli/configuration.rb:28:in `parse!'
    /Users/jonas/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:66:in `block in configuration'
    /Users/jonas/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:65:in `tap'
    /Users/jonas/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:65:in `configuration'
    /Users/jonas/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:29:in `execute!'
    /Users/jonas/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-2.1.0/bin/cucumber:8:in `<top (required)>'
    /Users/jonas/.rbenv/versions/2.1.5/bin/cucumber:23:in `load'
    /Users/jonas/.rbenv/versions/2.1.5/bin/cucumber:23:in `<main>'

It looks like Cuke's option parser parses the `-S` as a cukes arg, while in reality it's just for telling ruby to use PATH (whatever that means).

The source of the command is what's generated by `Cucumber::Rake::Task`, so don't blame me for using it, hehe:

    Cucumber::Rake::Task.new(:cucumber_wip) do |t|
      t.cucumber_opts = "--wip --tags @wip"
    end

**Comment by jonasschneider** [comment]
Nope, just me getting confused over cucumber profiles (I set `-S` somewhere globally). Sorry!
