### ISSUE TITLE
Fail, cucumber can not found require 'mysql2'. 

### ISSUE THREAD

**Issue by Douvi** [cucumber/cucumber-ruby#936]
I'm using cucumber + calablash-ios, to run my test. I have to use cucumber 1.3.20 because of calablash-ios do not use the last version of cucumber. On my test I need to clean my Mysql.

So, when I try to run my test, cucumber tell me it can not found the "require 'mysql2'". However when I run the same code directly in ruby. I can clean my DB with no issue...

Into my file "login.feature"

          Scenario: Setup the DB for the feature
                 Given We will clean tabe user with relation

Into my file "login_steps.rb"

         Given(/^We will clean tabe user with relation$/) do
               @sql = UserSQL.new()
               @sql.clear_table()
         end

Into my file "userSQL.rb"

         require 'mysql2'
         class UserSQL
                 def initialize()
		       @client = Mysql2::Client.new(:host => "localhost", :port => 8889)  	
	         end

  	         def clear_table()
		        DB_UTIL.instance.query("TRUNCATE TABLE user;")
                 end 
         end

Error :
/Users/me/project/features/userSQL.rb:2:in `require'
/Users/me/project/features/userSQL.rb:2:in `<top (required)>'
/Users/me/.rvm/gems/ruby-2.2.1/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:95:in `load'
/Users/me/.rvm/gems/ruby-2.2.1/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:95:in `load_code_file'
/Users/me/.rvm/gems/ruby-2.2.1/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/Users/me/.rvm/gems/ruby-2.2.1/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/Users/me/.rvm/gems/ruby-2.2.1/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:82:in `each'
/Users/me/.rvm/gems/ruby-2.2.1/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/Users/me/.rvm/gems/ruby-2.2.1/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:184:in `load_step_definitions'
/Users/me/.rvm/gems/ruby-2.2.1/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:42:in `run!'
/Users/me/.rvm/gems/ruby-2.2.1/gems/cucumber-1.3.20/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/me/.rvm/gems/ruby-2.2.1/gems/cucumber-1.3.20/bin/cucumber:13:in `<top (required)>'
/Users/me/.rvm/gems/ruby-2.2.1/bin/cucumber:23:in `load'
/Users/me/.rvm/gems/ruby-2.2.1/bin/cucumber:23:in `<main>'
/Users/me/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/me/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by Douvi** [comment]
Forgot to add this line into my Gemfile :

       gem 'mysql2', '~> 0.4.2'
